# Generated by Django 4.0.6 on 2022-07-18 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('setor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=25)),
                ('valor_custo', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('qtd_estoque', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='EquipamentoSetor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validade', models.IntegerField(default=1)),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='equipamento.equipamento')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='setor.setor')),
            ],
        ),
        migrations.AddField(
            model_name='equipamento',
            name='setores',
            field=models.ManyToManyField(through='equipamento.EquipamentoSetor', to='setor.setor'),
        ),
    ]
