# Generated by Django 4.0.6 on 2022-07-20 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setor', '0001_initial'),
        ('equipamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='descricao',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='equipamentosetor',
            name='equipamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipamento.equipamento'),
        ),
        migrations.AlterField(
            model_name='equipamentosetor',
            name='setor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setor.setor'),
        ),
    ]
